spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datajpa
    username: postgres
    password: 1111

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type: TRACE