spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datajpa
    username: postgres
    password: 1111

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        # default_batch_fetch_size: 100
        format_sql: true
        # show_sql: true

  # paging (default 값 글로벌 설정)
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        # one-indexed-parameters: true       # 인덱스 1부터 시작 -> 문제점 있음

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace