spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5432/security

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
